name: Gateways-Gateway-YARP-Pipeline
on:
  push:
    paths:
      - src/Gateway/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/Gateways/Gateway.YARP/Gateway.YARP.csproj
      - name: Build
        run: dotnet build src/Gateways/Gateway.YARP/Gateway.YARP.csproj --no-restore
      - name: Test
        run: dotnet test src/Gateways/Gateway.YARP/Gateway.YARP.csproj --no-build --verbosity normal
