name: Generate Changelog and Release
'on':
  push:
    tags:
      - v*
permissions: write-all
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          output-file: CHANGELOG.md
          tag-prefix: v
      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: '${{ steps.changelog.outputs.tag }}'
          release_name: '${{ steps.changelog.outputs.tag }}'
          body: '${{ steps.changelog.outputs.clean_changelog }}'
