name: Release
'on':
  push:
    branches:
      - release

permissions: write-all

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: '${{ secrets.github_token }}'
          create-summary: true
          skip-on-empty: false

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.github_token }}'
        with:
          tag_name: '${{ steps.changelog.outputs.tag }}'
          release_name: '${{ steps.changelog.outputs.tag }}'
          body: '${{ steps.changelog.outputs.clean_changelog }}'
