name: Services-User-API-Pipeline
on:
  push:
    paths:
      - src/Services/Users/User.API/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/Services/Users/User.API
      - name: Build
        run: dotnet build src/Services/Users/User.API --no-restore
      - name: Test
        run: dotnet test src/Services/Users/User.API --no-build --verbosity normal
